FROM alpine:latest

RUN apk update
RUN apk add nginx
RUN apk add openrc
RUN apk add curl
RUN apk add net-tools
RUN rm -f /etc/nginx/nginx.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /var/www/

EXPOSE 8080

CMD ["/usr/sbin/nginx","-c", "/etc/nginx/nginx.conf"]



