---
- name: Install EPEL repo
  yum:
    name: epel-release
    state: present

- name: apt install nginx
  import_tasks: debian.yml
  when: ansible_os_family | lower == 'debian' 
  notify:
    - restarted nginx


- name: yum install nginx
  import_tasks: redhat.yml
  when: ansible_os_family | lower == 'redhat'
  notify:
    - restarted nginx

- name: create Nginx config from template
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf 
  notify:
    - reload nginx  
